[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.0"
bson = "3.1.0"
dotenv = "0.15.0"
futures = "0.3.31"
futures-util = "0.3.31"
mongodb = "3.4.1"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
